blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Support Server
    url: https://discord.gg/UvEYbFd2rj
    about: For questions and support, please join our Discord server and open a ticket.
